
* TODO Introduction
Blargh! Fill me in!

* TODO Using Emacs as a text editor
Blargh! Fill me in!

* Hello, World and Beyond!
** First program

We're going to begin with the obligatory "Hello, World!" program. It looks like this.

#+begin_src haskell :tangle hello.hs

main :: IO ()
main = putStrLn "Hello, World!"

#+end_src

The first line is the type signature. It shows us that our program is going to involve some sort of input or output. The second line lets us know exactly what that output is going to be. Namely, "Hello, World!"

** Second program

Our second program will be similar, but will give you a personalized greeting. It looks like this. See if you can guess what it does before you run it.

#+begin_src haskell :tangle basic-greeting.hs

main :: IO ()
main = do
  putStrLn "What is your name?"
  name <- getLine
  putStrLn ("Hello, " ++ name ++ "!")

#+end_src

** Third program

Our third program will involve making a decision based on input.

#+begin_src haskell :tangle decision-greeting.hs

main = do
  putStrLn "Please enter \"R\" or \"r\" if you want me to be rude\n\
           \Anything else if you want me to be polite. :-)"
  rude <- getLine
  putStrLn $ greeting rude
    where
      greeting "R" = greeting "r"
      greeting "r" = "Blah! You suck!"
      greeting _   = "Hello, good sir/ma'am!"

#+end_src

** Fourth program

Our third program will be a touch more involved, but will use the same principles. Here, we are going to give the choice of being polite or rude to the user, and respond to some more info. Let's see if you can guess what the whole thing does before you run it.

Before we begin, we need our imports:

#+begin_src haskell :tangle involved-greeting.hs

import Text.Printf

#+end_src

Here is the general structure of the program:

#+begin_src haskell :tangle involved-greeting.hs

main :: IO ()
main = do
  putStrLn initialGreeting
  politenessInput <- getLine
  let shouldBePolite = inferPolite politenessInput
  putStrLn $ nameGreeting shouldBePolite
  nameInput <- getLine
  putStrLn $ locationGreeting shouldBePolite nameInput
  locationInput <- getLine
  putStrLn $ finalGreeting shouldBePolite nameInput locationInput

#+end_src

Here's the initial greeting we give our user. We also make a data type that tells us whether we should be polite or not:

#+begin_src haskell :tangle involved-greeting.hs

initialGreeting :: String
initialGreeting =
  "Hello, Dear User, would you like for me to be polite or rude today?\n\
  \Please type 1 for 'rude', and anything else for 'polite'."

data ShouldBePolite = Yes
                    | No

inferPolite :: String -> ShouldBePolite
inferPolite input = stringToPolite input
  where
    stringToPolite "1" = No
    stringToPolite _ = Yes

#+end_src

Now, we ask the user for his or her name:

#+begin_src haskell :tangle involved-greeting.hs

nameGreeting :: ShouldBePolite -> String
nameGreeting Yes =
  "Hello, good sir/ma'am. Pardon me for the intrusion, but what is your name?"
nameGreeting No =
  "Hey, jerk! What's yer name?"

#+end_src

Now, we prompt for location:

#+begin_src haskell :tangle involved-greeting.hs

locationGreeting :: ShouldBePolite -> String -> String
locationGreeting Yes name =
  printf "So sorry, but I'm quite curious, %s. \
         \Where are you from?" name
locationGreeting No  name =
  printf "You look funny, %s! Where ya from?" name

#+end_src

Now, we compose our final greeting:

#+begin_src haskell :tangle involved-greeting.hs

finalGreeting :: ShouldBePolite -> String -> String -> String
finalGreeting Yes name location =
  printf "How lovely, %s!\n\
         \I have an immense appreciation for folks from %s!" name location
finalGreeting No name location =
  printf "Ya better watch yer back, %s!\n\
         \We don't like folks from %s around here!\n\
         \They stink and don't belong with proper folk like us!" name location

#+end_src

